### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by DieracDelta** [Orlandster1998/vue-typed-js#2]
Your "Default Import" section doesn't quite work for me. In order for the component to be recognized post entry-point, I had to import and use the entire module. I guess what I'm trying to say is that I think the default import snippet doesn't need brackets--e.g.

```javascript
import Vue from 'vue'
import VueTypedJs from 'vue-typed-js'

Vue.use(VueTypedJs) 
```

**Comment by capaci** [comment]
I had the same issue and did the same as @DieracDelta and it works.

Thanks @DieracDelta !

**Comment by patientplatypus** [comment]
Yes, this is a silly thing - please change this in the documentation on the front page.

**Comment by gerwinov** [comment]
I had the same issue. The suggestion as provided by @DieracDelta worked for me as well.
